# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: opentracker_development
  encoding: unicode
  pool: 5
  timeout: 5000
  username: opentracker
  password: <%= Rails.application.secrets.db_password %>

test:
  adapter: postgresql
  database: opentracker_test
  encoding: unicode
  pool: 5
  timeout: 5000
  username: opentracker
  password: <%= Rails.application.secrets.db_password %>

production:
  adapter: postgresql
  database: opentracker_test
  encoding: unicode
  pool: 5
  timeout: 5000
  username: opentracker
  password: <%= Rails.application.secrets.db_password %>